SELECT CART_ID
FROM CART_PRODUCTS AS A
WHERE EXISTS (
    SELECT 1
    FROM CART_PRODUCTS AS B
    WHERE A.CART_ID = B.CART_ID AND NAME = 'Milk'
) AND EXISTS (
    SELECT 1
    FROM CART_PRODUCTS AS B
    WHERE A.CART_ID = B.CART_ID AND NAME = 'Yogurt'
)
GROUP BY CART_ID
ORDER BY CART_ID;