WITH FIRST_GEN AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
)
, SECOND_GEN AS (
    SELECT ED.ID
    FROM ECOLI_DATA ED
    JOIN FIRST_GEN FG ON FG.ID = ED.PARENT_ID
)
SELECT ED.ID
FROM ECOLI_DATA ED
JOIN SECOND_GEN SG ON SG.ID = ED.PARENT_ID
ORDER BY ED.ID;